import type { SpreadsheetColumnId } from "./column-ids";

export const SPREADSHEET_COLUMN_LABELS: Record<SpreadsheetColumnId, string> = {
  id: "Identifiant dossier",
  adherentRole: "Pour qui",
  wasSqyMemberLastYear: "Adhérent l'an dernier",
  ffttLicense: "Licence",
  ffttLicenseLookup: "Données licence",
  firstName: "Prénom",
  lastName: "Nom",
  sex: "Sexe",
  birthCity: "Ville de naissance",
  birthDate: "Date de naissance",
  adherentEmail: "E-mail adhérent",
  adherentPhonePrimary: "Téléphone principal",
  adherentPhoneSecondary: "Téléphone secondaire",
  addressLine1: "Adresse (ligne 1)",
  addressLine2: "Adresse (ligne 2)",
  postalCode: "Code postal",
  city: "Ville",
  representatives: "Représentants légaux",
  mainSectionId: "Section principale",
  additionalSectionIds: "Sections complémentaires",
  slotIds: "Créneaux",
  schoolPickupSlotIds: "Créneaux sortie école",
  medicalCertificateDeclaration: "Déclaration certificat médical",
  medicalQuestionnaire: "Questionnaire médical",
  medicalVeteranPath: "Parcours vétéran",
  medicalCertificateStatus: "Statut certificat médical",
  medicalCertificateStatusUpdatedAt: "Certificat mis à jour le",
  medicalCertificateStatusUpdatedBy: "Certificat mis à jour par",
  wantsRegistrationCertificate: "Attestation d'inscription",
  familyRegistrationOrder: "Rang dans la famille",
  reductionTypes: "Réductions",
  reductionReferenceCodes: "Codes réduction",
  firstFemaleRegistrationSqy: "Première femme SQY",
  photoConsent: "Droit à l'image",
  emergencyMedicalAuthorization: "Autorisation soins urgents",
  supervisionAcknowledgement: "Engagement encadrement",
  internalRulesAccepted: "Règlement intérieur",
  wantsCompetitorExtras: "Options compétiteur",
  competitionJerseySize: "Taille maillot compétition",
  wantsOptionalJersey: "Maillot optionnel",
  optionalJerseySize: "Taille maillot optionnel",
  competitionIds: "Compétitions",
  applicantNotes: "Précisions inscrit",
  isMinor: "Mineur",
  submitterUid: "Soumettant du dossier",
  submitterAccountEmail: "E-mail compte soumettant",
  schemaVersion: "Version schéma",
  status: "Statut dossier",
  reviewNotes: "Notes secrétariat",
  paymentAmountCents: "Montant paiement (centimes)",
  paymentRequestedAt: "Paiement demandé le",
  paymentRequestedBy: "Paiement demandé par",
  paymentEmailSentTo: "E-mail paiement envoyé à",
  stripeCheckoutSessionId: "Session Stripe",
  stripeCheckoutUrl: "URL paiement Stripe",
  stripeInvoiceId: "Facture Stripe",
  paymentStatus: "Statut paiement",
  paidAt: "Payé le",
  pricingQuote: "Devis",
  pricingQuoteStatus: "Statut devis",
  pricingQuoteComputedAt: "Devis calculé le",
  handisportPracticeLevel: "Niveau handisport",
  paymentStripeLineItems: "Lignes Stripe",
  payment: "Suivi paiement",
  paymentMethod: "Mode de paiement",
  paymentInstallments: "Échéances",
  paymentAids: "Aides",
  holidayVoucherAmountCents: "Chèques vacances (centimes)",
  remainingPaymentMethod: "Solde à régler par",
  paymentNote: "Note paiement",
  specialPaymentNote: "Note paiement spéciale",
  voluntaryDonationCents: "Don libre (centimes)",
  donationDiscountCents: "Remise don (centimes)",
  submittedAt: "Soumis le",
  updatedAt: "Mis à jour le",
};
