import { NextApiRequest, NextApiResponse } from "next";
import { MatchData } from "@/lib/shared/team-sync";
import {
  calculateTeamBurnout,
  DEFAULT_BURNOUT_CONDITIONS,
} from "@/lib/shared/burnout-conditions";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    // Créer des données de test simulées
    const testMatches: MatchData[] = [
      {
        id: "test_match_1",
        ffttId: "test_match_1",
        teamId: "test_team_1",
        opponent: "Équipe A",
        opponentClub: "Club A",
        date: new Date("2025-01-01"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "1",
        scoreA: 8,
        scoreB: 4,
        lien: "test_link_1",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "111111",
            nom: "SMITH",
            prenom: "John",
            points: 1300,
            sexe: "M",
            club: "Club A",
          },
          {
            licence: "222222",
            nom: "JOHNSON",
            prenom: "Mike",
            points: 1250,
            sexe: "M",
            club: "Club A",
          },
          {
            licence: "333333",
            nom: "WILLIAMS",
            prenom: "David",
            points: 1150,
            sexe: "M",
            club: "Club A",
          },
          {
            licence: "444444",
            nom: "BROWN",
            prenom: "Tom",
            points: 1050,
            sexe: "M",
            club: "Club A",
          },
        ],
      },
      {
        id: "test_match_2",
        ffttId: "test_match_2",
        teamId: "test_team_1",
        opponent: "Équipe B",
        opponentClub: "Club B",
        date: new Date("2025-01-02"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "2",
        scoreA: 6,
        scoreB: 6,
        lien: "test_link_2",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "555555",
            nom: "JONES",
            prenom: "Bob",
            points: 1200,
            sexe: "M",
            club: "Club B",
          },
          {
            licence: "666666",
            nom: "GARCIA",
            prenom: "Carlos",
            points: 1150,
            sexe: "M",
            club: "Club B",
          },
          {
            licence: "777777",
            nom: "MILLER",
            prenom: "Steve",
            points: 1100,
            sexe: "M",
            club: "Club B",
          },
          {
            licence: "888888",
            nom: "DAVIS",
            prenom: "Mark",
            points: 1000,
            sexe: "M",
            club: "Club B",
          },
        ],
      },
      {
        id: "test_match_3",
        ffttId: "test_match_3",
        teamId: "test_team_1",
        opponent: "Équipe C",
        opponentClub: "Club C",
        date: new Date("2025-01-03"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "3",
        scoreA: 8,
        scoreB: 2,
        lien: "test_link_3",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "999999",
            nom: "RODRIGUEZ",
            prenom: "Luis",
            points: 1000,
            sexe: "M",
            club: "Club C",
          },
          {
            licence: "000000",
            nom: "MARTINEZ",
            prenom: "Jose",
            points: 950,
            sexe: "M",
            club: "Club C",
          },
          {
            licence: "111111",
            nom: "HERNANDEZ",
            prenom: "Miguel",
            points: 900,
            sexe: "M",
            club: "Club C",
          },
          {
            licence: "222222",
            nom: "LOPEZ",
            prenom: "Antonio",
            points: 850,
            sexe: "M",
            club: "Club C",
          },
        ],
      },
      {
        id: "test_match_4",
        ffttId: "test_match_4",
        teamId: "test_team_1",
        opponent: "Équipe D",
        opponentClub: "Club D",
        date: new Date("2025-01-04"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "4",
        scoreA: 7,
        scoreB: 5,
        lien: "test_link_4",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "333333",
            nom: "GONZALEZ",
            prenom: "Juan",
            points: 1100,
            sexe: "M",
            club: "Club D",
          },
          {
            licence: "444444",
            nom: "WILSON",
            prenom: "James",
            points: 1050,
            sexe: "M",
            club: "Club D",
          },
          {
            licence: "555555",
            nom: "ANDERSON",
            prenom: "Robert",
            points: 1000,
            sexe: "M",
            club: "Club D",
          },
          {
            licence: "666666",
            nom: "THOMAS",
            prenom: "William",
            points: 950,
            sexe: "M",
            club: "Club D",
          },
        ],
      },
      {
        id: "test_match_5",
        ffttId: "test_match_5",
        teamId: "test_team_1",
        opponent: "Équipe E",
        opponentClub: "Club E",
        date: new Date("2025-01-05"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "5",
        scoreA: 8,
        scoreB: 3,
        lien: "test_link_5",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "777777",
            nom: "TAYLOR",
            prenom: "Michael",
            points: 1200,
            sexe: "M",
            club: "Club E",
          },
          {
            licence: "888888",
            nom: "MOORE",
            prenom: "Christopher",
            points: 1150,
            sexe: "M",
            club: "Club E",
          },
          {
            licence: "999999",
            nom: "JACKSON",
            prenom: "Daniel",
            points: 1100,
            sexe: "M",
            club: "Club E",
          },
          {
            licence: "000000",
            nom: "MARTIN",
            prenom: "Matthew",
            points: 1050,
            sexe: "M",
            club: "Club E",
          },
        ],
      },
      {
        id: "test_match_6",
        ffttId: "test_match_6",
        teamId: "test_team_1",
        opponent: "Équipe F",
        opponentClub: "Club F",
        date: new Date("2025-01-06"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "6",
        scoreA: 6,
        scoreB: 6,
        lien: "test_link_6",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "111111",
            nom: "LEE",
            prenom: "Anthony",
            points: 1100,
            sexe: "M",
            club: "Club F",
          },
          {
            licence: "222222",
            nom: "PEREZ",
            prenom: "Mark",
            points: 1050,
            sexe: "M",
            club: "Club F",
          },
          {
            licence: "333333",
            nom: "THOMPSON",
            prenom: "Donald",
            points: 1000,
            sexe: "M",
            club: "Club F",
          },
          {
            licence: "444444",
            nom: "WHITE",
            prenom: "Steven",
            points: 950,
            sexe: "M",
            club: "Club F",
          },
        ],
      },
      {
        id: "test_match_7",
        ffttId: "test_match_7",
        teamId: "test_team_1",
        opponent: "Équipe G",
        opponentClub: "Club G",
        date: new Date("2025-01-07"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "7",
        scoreA: 8,
        scoreB: 1,
        lien: "test_link_7",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "555555",
            nom: "HARRIS",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "Club G",
          },
          {
            licence: "666666",
            nom: "SANCHEZ",
            prenom: "Andrew",
            points: 950,
            sexe: "M",
            club: "Club G",
          },
          {
            licence: "777777",
            nom: "CLARK",
            prenom: "Joshua",
            points: 900,
            sexe: "M",
            club: "Club G",
          },
          {
            licence: "888888",
            nom: "RAMIREZ",
            prenom: "Kenneth",
            points: 850,
            sexe: "M",
            club: "Club G",
          },
        ],
      },
      {
        id: "test_match_8",
        ffttId: "test_match_8",
        teamId: "test_team_1",
        opponent: "Équipe H",
        opponentClub: "Club H",
        date: new Date("2025-01-08"),
        location: "SQY Ping",
        isHome: true,
        isExempt: false,
        isForfeit: false,
        phase: "aller",
        journee: "8",
        scoreA: 7,
        scoreB: 4,
        lien: "test_link_8",
        createdAt: new Date(),
        updatedAt: new Date(),
        joueursSQY: [
          {
            licence: "123456",
            nom: "DUPONT",
            prenom: "Jean",
            points: 1200,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "789012",
            nom: "MARTIN",
            prenom: "Pierre",
            points: 1100,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "345678",
            nom: "DURAND",
            prenom: "Paul",
            points: 1000,
            sexe: "M",
            club: "SQY PING",
          },
          {
            licence: "901234",
            nom: "BERNARD",
            prenom: "Jacques",
            points: 950,
            sexe: "M",
            club: "SQY PING",
          },
        ],
        joueursAdversaires: [
          {
            licence: "999999",
            nom: "LEWIS",
            prenom: "Kevin",
            points: 1100,
            sexe: "M",
            club: "Club H",
          },
          {
            licence: "000000",
            nom: "ROBINSON",
            prenom: "Brian",
            points: 1050,
            sexe: "M",
            club: "Club H",
          },
          {
            licence: "111111",
            nom: "WALKER",
            prenom: "George",
            points: 1000,
            sexe: "M",
            club: "Club H",
          },
          {
            licence: "222222",
            nom: "YOUNG",
            prenom: "Edward",
            points: 950,
            sexe: "M",
            club: "Club H",
          },
        ],
      },
    ];

    // Calculer les conditions de brûlage
    const burnoutInfos = calculateTeamBurnout(
      "test_team_1",
      "SQY PING 1 - Phase 1",
      testMatches,
      DEFAULT_BURNOUT_CONDITIONS
    );

    // Séparer les joueurs à risque et les autres
    const atRiskPlayers = burnoutInfos.filter((info) => info.isAtRisk);
    const safePlayers = burnoutInfos.filter((info) => !info.isAtRisk);

    res.status(200).json({
      success: true,
      data: {
        teamId: "test_team_1",
        teamName: "SQY PING 1 - Phase 1",
        totalPlayers: burnoutInfos.length,
        atRiskPlayers: atRiskPlayers.length,
        safePlayers: safePlayers.length,
        players: {
          atRisk: atRiskPlayers,
          safe: safePlayers,
        },
        conditions: DEFAULT_BURNOUT_CONDITIONS,
        matches: testMatches.map((m) => ({
          id: m.id,
          journee: m.journee,
          date: m.date,
          opponent: m.opponent,
          result: m.result || "À VENIR",
        })),
      },
    });
  } catch (error) {
    console.error("❌ Erreur lors du test des conditions de brûlage:", error);
    res.status(500).json({
      error: "Internal server error",
      details: error instanceof Error ? error.message : "Unknown error",
    });
  }
}
